language: node_js

node_js:
  - node # latest node

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - ng build --prod --aot=
  - cp -r dist/* ./Docker/dist

notifications:
  email:
    on_failure: change
    on_success: change
