language: node_js

node_js:
  - node # latest node

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - ng build --prod --aot=false
  - mkdir ./Docker/dist
  - cp -r dist/* ./Docker/dist
  - docker build ./Docker/ -t jesielconceicao/app-template-angular
  - docker run -d -p 8080:8080 jesielconceicao/app-template-angular
  - docker ps -a

notifications:
  email:
    on_failure: change
    on_success: change

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push jesielconceicao/app-template-angular;
    fi
